import { assetCatalog, regressionEvents, type ActionKind, type CoreAsset, type TradeEvent } from '@/lib/whale-data';

type RawEvent = { id?: string; ticker?: string; action?: string; actor?: string; organization?: string; role?: string; responsible_people?: string[]; amount_usd?: number; amount_display?: string | null; shares?: number; occurred_at?: string; published_at?: string; lag_days?: number | null; source?: string; source_url?: string; evidence_grade?: string };
type RawAsset = { ticker?: string; market?: Record<string, unknown> | null; price_history?: Array<{ date?: string; open?: number; high?: number; low?: number; close?: number; volume?: number }> };
type RawConcentration = { ticker?: string; score?: number; actor_count?: number; group_count?: number; source_names?: string[]; event_count?: number; buy_amount_usd?: number; sell_amount_usd?: number; net_amount_usd?: number; increase_score?: number; decrease_score?: number; increase_actor_count?: number; decrease_actor_count?: number; increase_event_count?: number; decrease_event_count?: number; increase_source_names?: string[]; decrease_source_names?: string[] };
type RawHoldingConcentration = { ticker?: string; score?: number; holder_count?: number; source_count?: number; source_names?: string[]; position_count?: number; reported_value_usd?: number };
type RawWhale = { name?: string; category?: string; weight?: number; source?: string; role?: string; ticker?: string; source_url?: string; tracking_status?: string; filing_count?: number };
export type ActionPeriod = 'all' | '1y' | '6m' | '3m' | '1m';
export type SitePayload = { schema_version?: number; generated_at?: string; mode?: string; core_assets?: RawAsset[]; events?: RawEvent[]; holdings?: RawEvent[]; whale_universe?: RawWhale[]; concentration?: RawConcentration[]; concentration_periods?: Partial<Record<ActionPeriod, RawConcentration[]>>; holding_concentration?: RawHoldingConcentration[] };
export type ConcentrationRow = { ticker: string; score: number; increaseScore: number; decreaseScore: number; increaseActors: number; decreaseActors: number; increaseEvents: number; decreaseEvents: number; increaseSources: string[]; decreaseSources: string[]; increaseAmountUsd: number; decreaseAmountUsd: number; netAmountUsd: number };
export type HoldingRow = { ticker: string; score: number; holderCount: number; sourceCount: number; sourceNames: string[]; positionCount: number; valueUsd: number };
export type WhaleProfile = { name: string; category: '政界巨鲸' | '行政部门' | '公司关键人员' | '重点机构'; weight: number; source: string; role: string; ticker: string; sourceUrl: string; trackingStatus: 'scope_only' | 'disclosed'; filingCount: number; eventCount: number; holdings: TradeEvent[] };
export type SiteViewData = { mode: 'production' | 'regression'; generatedAt: string | null; assets: CoreAsset[]; events: TradeEvent[]; concentration: ConcentrationRow[]; concentrationPeriods: Record<ActionPeriod, ConcentrationRow[]>; holdingConcentration: HoldingRow[]; holdings: TradeEvent[]; whales: WhaleProfile[] };

const actions = new Set<ActionKind>(['BUY', 'SELL', 'NEW', 'ADD', 'REDUCE', 'EXIT']);
const numberValue = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? value : null;
export function formatMoney(value: number): string { const absolute = Math.abs(value); const sign = value < 0 ? '−' : ''; if (absolute >= 1_000_000_000) return `${sign}$${(absolute / 1_000_000_000).toFixed(2)}B`; if (absolute >= 1_000_000) return `${sign}$${(absolute / 1_000_000).toFixed(1)}M`; if (absolute >= 1_000) return `${sign}$${(absolute / 1_000).toFixed(0)}K`; return absolute ? `${sign}$${absolute.toLocaleString('en-US')}` : '金额未披露'; }

function mapEvent(raw: RawEvent): TradeEvent | null {
  const action = String(raw.action || '').toUpperCase() as ActionKind; const ticker = String(raw.ticker || '').toUpperCase();
  if (!actions.has(action) || !ticker) return null;
  const amountUsd = numberValue(raw.amount_usd) || 0;
  return { id: String(raw.id || `${ticker}-${raw.published_at || raw.occurred_at || 'event'}`), ticker, action, actor: String(raw.actor || 'Unknown filer'), organization: String(raw.organization || ''), role: String(raw.role || ''), responsiblePeople: Array.isArray(raw.responsible_people) ? raw.responsible_people.map(String) : [], amount: String(raw.amount_display || formatMoney(amountUsd)), amountUsd, instrument: raw.shares ? `${Number(raw.shares).toLocaleString('en-US')} shares` : '申报证券', occurredAt: String(raw.occurred_at || ''), publishedAt: String(raw.published_at || ''), lagDays: numberValue(raw.lag_days), source: String(raw.source || 'Public filing'), sourceUrl: String(raw.source_url || ''), evidence: raw.evidence_grade === 'A' ? 'A' : 'B' };
}

function regressionView(): SiteViewData {
  const counts = new Map<string, number>(); regressionEvents.forEach((event) => counts.set(event.ticker, (counts.get(event.ticker) || 0) + 1));
  const concentration = ['MSFT', 'INTC', 'UBER'].map((ticker, index) => ({ ticker, score: 40 - index * 4, increaseScore: 40 - index * 4, decreaseScore: 0, increaseActors: 1, decreaseActors: 0, increaseEvents: 1, decreaseEvents: 0, increaseSources: ['Congress PTR'], decreaseSources: [], increaseAmountUsd: regressionEvents.find((event) => event.ticker === ticker)?.amountUsd || 0, decreaseAmountUsd: 0, netAmountUsd: regressionEvents.find((event) => event.ticker === ticker)?.amountUsd || 0 }));
  return { mode: 'regression', generatedAt: null, assets: assetCatalog.map(([ticker, name, kind]) => ({ ticker, name, kind, price: null, change: null, signals: counts.get(ticker) || 0, priceHistory: [] })), events: regressionEvents, holdings: [], whales: [], holdingConcentration: [], concentration, concentrationPeriods: { all: concentration, '1y': concentration, '6m': concentration, '3m': concentration, '1m': concentration } };
}

function mapConcentration(rows: RawConcentration[] = []): ConcentrationRow[] { return rows.map((row) => ({ ticker: String(row.ticker || ''), score: Number(row.score || 0), increaseScore: Number(row.increase_score || 0), decreaseScore: Number(row.decrease_score || 0), increaseActors: Number(row.increase_actor_count || 0), decreaseActors: Number(row.decrease_actor_count || 0), increaseEvents: Number(row.increase_event_count || 0), decreaseEvents: Number(row.decrease_event_count || 0), increaseSources: Array.isArray(row.increase_source_names) ? row.increase_source_names.map(String) : [], decreaseSources: Array.isArray(row.decrease_source_names) ? row.decrease_source_names.map(String) : [], increaseAmountUsd: Number(row.buy_amount_usd || 0), decreaseAmountUsd: Number(row.sell_amount_usd || 0), netAmountUsd: Number(row.net_amount_usd || 0) })); }

function whaleCategory(source: string): WhaleProfile['category'] { if (source === 'OGE') return '行政部门'; if (source === 'Congress PTR') return '政界巨鲸'; if (source === 'SEC Form 4') return '公司关键人员'; return '重点机构'; }
function whaleWeight(category: WhaleProfile['category'], role: string): number { if (category === '政界巨鲸' || category === '行政部门') return 1; if (category === '重点机构') return .9; return /CEO|CFO|CIO|CHIEF EXECUTIVE|CHIEF FINANCIAL|CHAIR/i.test(role) ? 1 : .85; }
function buildWhales(events: TradeEvent[], holdings: TradeEvent[], universe: RawWhale[]): WhaleProfile[] {
  const profiles = new Map<string, WhaleProfile>();
  const eventCounts = new Map<string, number>();
  const holdingsByActor = new Map<string, TradeEvent[]>();
  for (const event of events) eventCounts.set(event.actor, (eventCounts.get(event.actor) || 0) + 1);
  for (const holding of holdings) holdingsByActor.set(holding.actor, [...(holdingsByActor.get(holding.actor) || []), holding]);
  for (const raw of universe) { const category = raw.category as WhaleProfile['category']; if (!raw.name || !['政界巨鲸', '行政部门', '公司关键人员', '重点机构'].includes(category)) continue; const name = String(raw.name); const current = profiles.get(name); if (current && current.category === category) { const role = String(raw.role || ''); const ticker = String(raw.ticker || ''); current.filingCount += Number(raw.filing_count || 0); if (raw.tracking_status === 'disclosed') current.trackingStatus = 'disclosed'; if (role && !current.role.includes(role)) current.role = `${current.role} / ${role}`; if (ticker && !current.ticker.split(',').includes(ticker)) current.ticker = [current.ticker, ticker].filter(Boolean).join(','); continue; } profiles.set(name, { name, category, weight: Number(raw.weight || whaleWeight(category, String(raw.role || ''))), source: String(raw.source || ''), role: String(raw.role || ''), ticker: String(raw.ticker || ''), sourceUrl: String(raw.source_url || ''), trackingStatus: raw.tracking_status === 'disclosed' ? 'disclosed' : 'scope_only', filingCount: Number(raw.filing_count || 0), eventCount: 0, holdings: [] }); }
  for (const item of [...events, ...holdings]) { const category = whaleCategory(item.source); const current = profiles.get(item.actor); const role = item.role || item.organization; if (!current) profiles.set(item.actor, { name: item.actor, category, weight: whaleWeight(category, role), source: item.source, role, ticker: item.ticker, sourceUrl: item.sourceUrl, trackingStatus: 'disclosed', filingCount: 1, eventCount: eventCounts.get(item.actor) || 0, holdings: holdingsByActor.get(item.actor) || [] }); else { current.trackingStatus = 'disclosed'; current.eventCount = eventCounts.get(item.actor) || 0; current.holdings = holdingsByActor.get(item.actor) || []; current.sourceUrl ||= item.sourceUrl; current.ticker ||= item.ticker; if (!current.role && role) current.role = role; } }
  return [...profiles.values()].sort((a, b) => b.weight - a.weight || b.eventCount - a.eventCount || a.name.localeCompare(b.name));
}

export function toSiteView(payload: SitePayload | null): SiteViewData {
  const events = (payload?.events || []).map(mapEvent).filter((event): event is TradeEvent => Boolean(event));
  const rawAssets = new Map((payload?.core_assets || []).map((asset) => [String(asset.ticker || '').toUpperCase(), asset]));
  const live = payload?.mode === 'production' && (events.length > 0 || (payload?.holdings || []).length > 0 || (payload?.core_assets || []).some((asset) => asset.market));
  if (!live) return regressionView();
  const counts = new Map<string, number>(); events.forEach((event) => counts.set(event.ticker, (counts.get(event.ticker) || 0) + 1));
  const assets = assetCatalog.map(([ticker, name, kind]) => { const raw = rawAssets.get(ticker); const market = raw?.market || {}; return { ticker, name, kind, price: numberValue(market.price), change: numberValue(market.change_pct), signals: counts.get(ticker) || 0, priceHistory: (raw?.price_history || []).flatMap((point) => { const close = numberValue(point.close); const open = numberValue(point.open) ?? close; const high = numberValue(point.high) ?? Math.max(open || 0, close || 0); const low = numberValue(point.low) ?? Math.min(open || 0, close || 0); const date = String(point.date || ''); return close && open && high && low && date >= '2025-01-01' ? [{ date, open, high, low, close, volume: numberValue(point.volume) || 0 }] : []; }) }; });
  const holdings = (payload?.holdings || []).map((raw) => mapEvent({ ...raw, action: 'ADD' })).filter((event): event is TradeEvent => Boolean(event));
  const concentration = mapConcentration(payload?.concentration || []);
  const periods = payload?.concentration_periods || {};
  return { mode: 'production', generatedAt: payload?.generated_at || null, assets, events, holdings, whales: buildWhales(events, holdings, payload?.whale_universe || []), concentration,
    concentrationPeriods: { all: mapConcentration(periods.all || payload?.concentration || []), '1y': mapConcentration(periods['1y'] || []), '6m': mapConcentration(periods['6m'] || []), '3m': mapConcentration(periods['3m'] || []), '1m': mapConcentration(periods['1m'] || []) },
    holdingConcentration: (payload?.holding_concentration || []).map((row) => ({ ticker: String(row.ticker || ''), score: Number(row.score || 0), holderCount: Number(row.holder_count || 0), sourceCount: Number(row.source_count || 0), sourceNames: Array.isArray(row.source_names) ? row.source_names.map(String) : [], positionCount: Number(row.position_count || 0), valueUsd: Number(row.reported_value_usd || 0) })) };
}
export const regressionSiteView = regressionView();
