'use client';

import { useState } from 'react';
import { ArrowLeft, Building2, CalendarClock, ExternalLink, ShieldCheck, TrendingDown, TrendingUp, Users } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ReferenceDot, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useSiteData } from '@/lib/use-site-data';
import type { ActionKind } from '@/lib/whale-data';

const labels: Record<ActionKind, string> = { BUY: '买入', SELL: '卖出', NEW: '新建仓', ADD: '加仓', REDUCE: '减仓', EXIT: '清仓' };
const shortLabels: Record<ActionKind, string> = { BUY: '买', SELL: '卖', NEW: '新', ADD: '加', REDUCE: '减', EXIT: '清' };
const colors: Record<ActionKind, string> = { BUY: '#42d7a4', SELL: '#ff9f43', NEW: '#42d7a4', ADD: '#58d6e7', REDUCE: '#ff9f43', EXIT: '#ff6b6b' };
const positiveActions = new Set<ActionKind>(['BUY', 'NEW', 'ADD']);

export function AssetDetail({ ticker }: { ticker: string }) {
  const { data } = useSiteData(); const asset = data.assets.find((item) => item.ticker === ticker) || data.assets[0];
  const [mode, setMode] = useState<'PUBLIC' | 'OCCURRED'>('PUBLIC'); const events = data.events.filter((event) => event.ticker === asset.ticker); const series = asset.priceHistory;
  const markers = series.length ? events.flatMap((event) => { const target = mode === 'PUBLIC' ? event.publishedAt : event.occurredAt; if (!target || target < series[0].date || target > series[series.length - 1].date) return []; const nearest = series.reduce((best, row) => Math.abs(Date.parse(row.date) - Date.parse(target)) < Math.abs(Date.parse(best.date) - Date.parse(target)) ? row : best, series[0]); return [{ ...event, pointDate: nearest.date, pointPrice: nearest.close }]; }) : [];
  const owners = new Set(events.map((event) => event.actor)).size; const institutions = new Set(events.map((event) => event.organization).filter(Boolean)).size; const maxLag = events.reduce((maximum, event) => Math.max(maximum, event.lagDays || 0), 0);

  return <main className="asset-page"><header className="asset-header"><a href="/" className="back-link"><ArrowLeft size={15} />返回行动雷达</a><div className="asset-header-note"><ShieldCheck size={14} />{data.mode === 'production' ? '生产数据 · 只展示可核验行动' : '历史回归样本 · 非实时'}</div></header>
    <section className="asset-hero"><div><p className="eyebrow">CORE ASSET / {asset.kind.toUpperCase()}</p><div className="asset-title"><h1>{asset.ticker}</h1><span>{asset.name}</span></div><p>真实价格走势与政界、机构和公司内部人的可验证行动叠加；默认按公众首次可获知日期展示。</p></div><div className="asset-price"><strong>{asset.price === null ? '行情待接入' : `$${asset.price.toLocaleString('en-US')}`}</strong>{asset.change !== null && <span className={asset.change >= 0 ? 'up' : 'down'}>{asset.change >= 0 ? '+' : ''}{asset.change.toFixed(2)}%</span>}</div></section>
    <section className="asset-layout"><section className="panel chart-panel"><div className="panel-heading chart-heading"><div><p className="kicker">PRICE × VERIFIED ACTIONS</p><h2>价格行动时间轴</h2></div><fieldset className="time-mode" aria-label="时间轴模式"><button className={mode === 'PUBLIC' ? 'selected' : ''} onClick={() => setMode('PUBLIC')}>公众获知日</button><button className={mode === 'OCCURRED' ? 'selected' : ''} onClick={() => setMode('OCCURRED')}>交易发生日</button></fieldset></div><div className="bias-notice"><CalendarClock size={16} /><span>{mode === 'PUBLIC' ? '可跟随视图：事件只在披露公开后出现，避免回看偏差。' : '事实回溯视图：用于研究真实发生时间，不代表当时公众已经知情。'}</span></div>
        {series.length > 1 ? <><div className="main-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={series} margin={{ top: 34, right: 24, bottom: 10, left: 2 }}><CartesianGrid vertical={false} stroke="rgba(145,182,204,.10)" /><XAxis dataKey="date" tick={{ fill: '#6f8796', fontSize: 9 }} tickLine={false} axisLine={false} minTickGap={38} /><YAxis dataKey="close" domain={['auto', 'auto']} orientation="right" tick={{ fill: '#6f8796', fontSize: 9 }} tickLine={false} axisLine={false} width={52} /><Tooltip contentStyle={{ background: '#0a1722', border: '1px solid rgba(145,182,204,.18)', borderRadius: 8, fontSize: 10 }} labelStyle={{ color: '#7891a1' }} formatter={(value) => [`$${Number(value).toLocaleString('en-US')}`, '收盘价']} /><Line type="monotone" dataKey="close" stroke="#58d6e7" strokeWidth={2.2} dot={false} isAnimationActive={false} />{markers.map((event) => <ReferenceDot key={event.id} x={event.pointDate} y={event.pointPrice} r={7} fill={colors[event.action]} stroke="#061019" strokeWidth={3} label={{ value: shortLabels[event.action], position: 'top', fill: colors[event.action], fontSize: 9, fontWeight: 800 }} />)}</LineChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="new-dot" />买入/新建</span><span><i className="add-dot" />确认加仓</span><span><i className="reduce-dot" />卖出/减仓</span><span><i className="exit-dot" />确认清仓</span></div>{markers.length > 0 && <div className="chart-event-rail" aria-label="图表行动标记明细">{markers.map((event) => { const positive = positiveActions.has(event.action); return <article className={`chart-event-chip ${positive ? 'positive' : 'negative'}`} key={`rail-${event.id}`}><span className="chart-event-icon">{positive ? <TrendingUp size={14} /> : <TrendingDown size={14} />}</span><div><time>{mode === 'PUBLIC' ? event.publishedAt : event.occurredAt}</time><strong>{labels[event.action]} · {event.actor}</strong><small>{event.amount} · ${event.pointPrice.toLocaleString('en-US')} 附近</small></div></article>; })}</div>}</> : <div className="chart-empty"><CalendarClock size={28} /><strong>尚无真实历史价格序列</strong><p>为了避免误导，这里不会用模拟曲线替代真实行情。生产扫描写入价格历史后，行动标记会自动叠加。</p></div>}
      </section><aside className="asset-sidebar"><section className="panel asset-stat-panel"><div><Users size={16} /><span>独立行动主体</span><strong>{owners}</strong></div><div><Building2 size={16} /><span>关联机构</span><strong>{institutions}</strong></div><div><CalendarClock size={16} /><span>最长披露延迟</span><strong>{maxLag ? `${maxLag}天` : '—'}</strong></div></section><section className="panel source-policy"><p className="kicker">ATTRIBUTION RULE</p><h2>归因规则</h2><p>个人申报归于实际交易人；机构 13F 归于申报机构。董事长、CEO、CFO、CIO 等关键岗位仅作为关系信息，不会被误写为个人交易。</p></section></aside></section>
    <section className="panel asset-events"><div className="panel-heading"><div><p className="kicker">EVIDENCE LEDGER</p><h2>{asset.ticker} 行动证据</h2></div><span className="window-pill">{events.length} 条记录</span></div>{events.length ? <div className="asset-event-list">{events.map((event) => <article key={event.id}><div className="event-action" style={{ color: colors[event.action] }}>{labels[event.action]}</div><div><strong>{event.actor}</strong><p>{event.organization} · {event.role}</p></div><div><strong>{event.amount}</strong><p>{event.instrument}</p></div><div><strong>发生 {event.occurredAt || '未披露'}</strong><p>公开 {event.publishedAt || '—'} · 延迟 {event.lagDays === null ? '未知' : `${event.lagDays} 天`}</p></div><div><span className={`evidence-grade grade-${event.evidence.toLowerCase()}`}>{event.evidence}</span>{event.sourceUrl ? <a className="source-link" href={event.sourceUrl} target="_blank" rel="noreferrer" title="打开原始披露"><ExternalLink size={14} /></a> : <span className="source-link disabled"><ExternalLink size={14} /></span>}</div></article>)}</div> : <div className="empty-ledger"><ShieldCheck size={24} /><strong>暂无通过证据门的行动记录</strong><p>不会用观点、传闻或无法验证的媒体推断填充空白。</p></div>}</section>
  </main>;
}
